language: python
services:
    - mysql
python:
    - "2.7"
install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pep8
    - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 ."
    - pyflakes -x W .
script:
    - make test
